// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbTable

import (
	"time"

	"gorm.io/gorm"
)

const TableNameComment = "comment"

// Comment 评论
type Comment struct {
	ID         int32          `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增的主键ID" json:"id"`          // 自增的主键ID
	UID        int32          `gorm:"column:uid;comment:用户ID" json:"uid"`                                         // 用户ID
	Content    string         `gorm:"column:content;comment:评论内容" json:"content"`                                 // 评论内容
	LikeCounts int32          `gorm:"column:like_counts;comment:点赞次数" json:"like_counts"`                         // 点赞次数
	CreatedTs  int32          `gorm:"column:created_ts;comment:创建时间戳" json:"created_ts"`                          // 创建时间戳
	CreatedAt  time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                           // 删除时间
	ParentID   int32          `gorm:"column:parent_id;comment:父评论id" json:"parent_id"`                            // 父评论id
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
