// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbTable

import (
	"time"
)

const TableNameVideoLog = "video_log"

// VideoLog mapped from table <video_log>
type VideoLog struct {
	ID                  int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID                 int32     `gorm:"column:uid;not null" json:"uid"`
	AddDate             time.Time `gorm:"column:add_date;not null;default:CURRENT_TIMESTAMP;comment:添加日期" json:"add_date"`       // 添加日期
	AddVideoName        string    `gorm:"column:add_video_name;not null;comment:添加视频名称" json:"add_video_name"`                   // 添加视频名称
	AddImgName          string    `gorm:"column:add_img_name;not null;comment:添加图片名称" json:"add_img_name"`                       // 添加图片名称
	Date                time.Time `gorm:"column:date;not null;comment:日期（YYYY-MM-DD）" json:"date"`                               // 日期（YYYY-MM-DD）
	AddImgDirectoryName string    `gorm:"column:add_img_directory_name;not null;comment:添加图片目录名称" json:"add_img_directory_name"` // 添加图片目录名称
}

// TableName VideoLog's table name
func (*VideoLog) TableName() string {
	return TableNameVideoLog
}
